import {registerScene, type SceneFeatures} from './sceneIndex';

const SCENE_CATALOG: SceneFeatures[] = [
  {
    id: 'dryFiltersScene',
    cardCount: 4,
    layout: '2L-2R',
    theme: 'dark',
    beatsUsed: ['appear', 'appearStaggered', 'highlightLines', 'recolorTokens', 'scanTableColumn', 'filterRows'],
    hasHighlight: true,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: true,
    duration: 45,
    description: 'Four code cards showing DRY violation in filter conditions. Table scanning animation highlights matching rows.',
    tags: ['code-comparison', 'table', 'filters', 'dry-violation', 'highlight'],
  },
  {
    id: 'dryKnowledgeScene',
    cardCount: 4,
    layout: '2L-1R',
    theme: 'dark',
    beatsUsed: ['appear', 'appearStaggered', 'highlightLines', 'recolorLine', 'knowledgeScan', 'zoomReveal', 'crossfade'],
    hasHighlight: true,
    hasZoom: true,
    hasTypewriter: false,
    hasCrossfade: true,
    hasTable: false,
    duration: 60,
    description: 'Three code mappers with knowledge duplication. Scan highlights same case across cards, break animation shows inconsistency, fourth card reveals unified solution.',
    tags: ['code-comparison', 'knowledge', 'mappers', 'dry-violation', 'highlight', 'zoom'],
  },
  {
    id: 'introMergeScene',
    cardCount: 0,
    layout: null,
    theme: 'dark',
    beatsUsed: ['appear', 'disappear', 'moveTo'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: false,
    duration: 30,
    description: 'Code lines merge from sides to center. Timelapse effect at end.',
    tags: ['intro', 'merge', 'animation', 'code-lines'],
  },
  {
    id: 'chapter1IntroScene',
    cardCount: 0,
    layout: 'center-title',
    theme: 'dark',
    beatsUsed: ['titleFade'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: false,
    duration: 4,
    description: 'Chapter 1 title: COMMON CONDITIONS TRAP. Pink chapter number.',
    tags: ['intro', 'title', 'chapter'],
  },
  {
    id: 'chapter2IntroScene',
    cardCount: 0,
    layout: 'center-title',
    theme: 'dark',
    beatsUsed: ['titleFade', 'swipeReveal'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: false,
    duration: 5,
    description: 'Chapter 2 title: ONE SHAPE TWO MEANINGS. Swipe reveal transition.',
    tags: ['intro', 'title', 'chapter', 'transition'],
  },
  {
    id: 'chapter3IntroScene',
    cardCount: 0,
    layout: 'center-title',
    theme: 'dark',
    beatsUsed: ['titleFade'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: false,
    duration: 4,
    description: 'Chapter 3 title: ONE DTO THREE LAYERS.',
    tags: ['intro', 'title', 'chapter'],
  },
  {
    id: 'paymentInputsScene',
    cardCount: 2,
    layout: 'split-vertical',
    theme: 'mixed',
    beatsUsed: ['appear', 'morphBetween'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: false,
    duration: 25,
    description: 'Split screen with light/dark themes. Payment form inputs morph between views.',
    tags: ['form', 'inputs', 'split-screen', 'morph'],
  },
  {
    id: 'splitDtoScene',
    cardCount: 3,
    layout: 'split-vertical',
    theme: 'mixed',
    beatsUsed: ['appear', 'morphRect', 'morphGradient'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: false,
    hasCrossfade: false,
    hasTable: false,
    duration: 40,
    description: 'DTO splits into domain model and entity. Three-layer architecture visualization.',
    tags: ['dto', 'architecture', 'split', 'layers', 'morph'],
  },
  {
    id: 'typewriterCodeScene',
    cardCount: 0,
    layout: 'center',
    theme: 'dark',
    beatsUsed: ['typewriter', 'cursorBlink', 'disappear'],
    hasHighlight: false,
    hasZoom: false,
    hasTypewriter: true,
    hasCrossfade: false,
    hasTable: false,
    duration: 15,
    description: 'Quote typed character by character. Cursor blinks after text disappears.',
    tags: ['quote', 'typewriter', 'outro', 'cursor'],
  },
];

export function initSceneRegistry(): void {
  for (const scene of SCENE_CATALOG) {
    registerScene(scene);
  }
}

export function getSceneCatalog(): SceneFeatures[] {
  return [...SCENE_CATALOG];
}

